name: ollygemini
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.30.1


  cupertino_icons: ^1.0.2

  firebase_auth: ^4.19.4
  google_generative_ai: ^0.2.2
  google_fonts: 6.1.0
  flutter_dotenv: ^5.1.0
  google_gemini: ^0.1.2
  image_picker: ^1.0.7
  #lottie: ^3.1.0
  lottie: ^3.1.0
  cloud_firestore: ^4.17.2
  firebase_storage: ^11.7.4


dev_dependencies:
  flutter_test:
    sdk: flutter
    #

  flutter_lints: ^2.0.0
 
flutter:
 
  uses-material-design: true
 
  assets:
    - .env
    - assets/
    - assets/images/water.jpg
    - assets/bubble.json
    - assets/images/brobot.png
    - assets/images/chat1.png
    - assets/images/bigbot.png
    - assets/images/signin.png
    - assets/images/signup.png
    - assets/images/facebook.png
    - assets/images/google.png
    - assets/images/woman2.png
    - assets/images/woman.png
    - assets/images/moon.png
    - assets/images/reset1.png

    

  